# Generated by Django 6.0.5 on 2026-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=15),
        ),
    ]
