# Generated by Django 6.0.5 on 2026-06-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DEP', 'Deposit'), ('WIT', 'Withdraw')], max_length=4),
        ),
    ]
